## Exploratory Data Analysis of Stack Overflow Annual Developer Survey

### Stack Overflow
Stack Overflow is a question-and-answer website for programmers. It is the flagship site of the Stack Exchange Network. It was created in 2008 by Jeff Atwood and Joel Spolsky. It features questions and answers on certain computer programming topics. It was created to be a more open alternative to earlier question and answer websites such as Experts-Exchange.

### Dataset

The following dataset is downloaded from official site of stackoverflow. [survery link]( https://insights.stackoverflow.com/survey)

### TODO List:

- Basic Prerequisites Steps to Check the Dataframe
- Drop Unnecessary Columns
- Handling Missing Values
- Replacing Main Branch columns values to Development Type
- Replacing values of Age Columns
- Editing Employement Type, Education Type and Organization Size columns value.
- Changing Learncode column to Mode of Learning
- Rename columns
- Create Label Bins for Work Experience and Professional Coding Experience Column
- Analysing Final DataFrame Data

In [1]:
# Import relevant packages
import pandas as pd

In [2]:
#Setting the columns display option as maximum and float display format
pd.set_option('display.max_column', None)
pd.set_option('display.max_colwidth', None)
pd.options.display.float_format = '{:.2f}'.format

In [3]:
#Reading Dataframe
df = pd.read_csv('survey_results_public.csv')

#### TODO - 1: - Basic Prerequisites Steps to Check the Dataframe

In [4]:
df.head(3)

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Bootstrapping a business;Professional development or self-paced learning from online courses,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;Colleague;Friend or family member;Hackathons (virtual or in-person);Online Courses or Certification;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;Books;Recorded coding sessions;How-to videos;Video-based Online Courses;Written-based Online Courses;Auditory material (e.g., podcasts);Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work with;Visit developer communities like Stack Overflow;Other (please specify):,United States of America,USD\tUnited States dollar,285000.00,HTML/CSS;JavaScript;Python,Bash/Shell (all shells);C#;Dart;Elixir;GDScript;HTML/CSS;JavaScript;Rust,Supabase,Firebase Realtime Database;Supabase,Amazon Web Services (AWS);Netlify;Vercel,Fly.io;Netlify;Render,Next.js;React;Remix;Vue.js,Deno;Elm;Nuxt.js;React;Svelte;Vue.js,Electron;React Native;Tauri,Capacitor;Electron;Tauri;Uno Platform;Xamarin,Docker;Kubernetes;npm;Pip;Vite;Webpack;Yarn,Godot;npm;pnpm;Unity 3D;Unreal Engine;Vite;Webpack;Yarn,Vim;Visual Studio Code,Vim;Visual Studio Code,iOS;iPadOS;MacOS;Windows;Windows Subsystem for Linux (WSL),MacOS;Windows;Windows Subsystem for Linux (WSL),Asana;Basecamp;GitHub Discussions;Jira;Linear;Notion;Trello,GitHub Discussions;Linear;Notion;Trello,Cisco Webex Teams;Discord;Google Chat;Google Meet;Signal;Skype;Slack;Telegram;Whatsapp;Zoom,Discord;Signal;Slack;Zoom,ChatGPT,ChatGPT;Neeva AI,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely","I don't think it's super necessary, but I think improving search and clarifying poorly worded questions would be useful (especially for moderators/editors).",Yes,Indifferent,Other (please explain),Somewhat distrust,Learning about a codebase;Writing code;Debugging and getting help,Writing code;Committing and reviewing code,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,10.00,Strongly agree,Agree,Strongly agree,Agree,Agree,Agree,Agree,Strongly agree,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testing;Observability tools,"Information Services, IT, Software Development, or other Technology",Appropriate in length,Easy,285000.00
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced learning from online courses,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;How-to videos;Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",NaN,27,23,"Developer, back-end","5,000 to 9,999 employees",I have some influence,Given a list,Start a free trial;Ask developers I know/work with;Visit developer communities like Stack Overflow,United States of America,USD\tUnited States dollar,250000.00,Bash/Shell (all shells);Go,Haskell;OCaml;Rust,NaN,NaN,Amazon Web Services (AWS);Google Cloud;OpenStack;VMware;Vultr,NaN,NaN,NaN,NaN,NaN,Cargo;Docker;Kubernetes;Make;Nix,Cargo;Kubernetes;Nix,Emacs;Helix,Emacs;Helix,MacOS;Other Linux-based,MacOS;Other Linux-based,Markdown File;Stack Overflow for Teams,Markdown File,Microsoft Teams;Slack;Zoom,Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow for Teams (private knowledge sharing & collaboration platform for companies),A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,23.00,Strongly agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Agree,Agree,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testing;Observability tools;Innersource initiative;Developer portal or other central places to find tools/services;Continuous integration (CI) and (more often) continuous delivery,"Information Services, IT, Software Development, or other Technology",Appropriate in length,Easy,250000.00

In [5]:
df.shape

(89184, 84)

In [6]:
#Checking basic statistics of numerical data
df.describe()

,ResponseId,CompTotal,WorkExp,ConvertedCompYearly
count,89184.00,48225.00,43579.00,48019.00
mean,44592.50,1036806635562467391394372602402550216392704.00,11.41,103110.08
std,25745.35,227684720124324374955124620267587368424308736.00,9.05,681418.84
min,1.00,0.00,0.00,1.00
25%,22296.75,63000.00,5.00,43907.00
50%,44592.50,115000.00,9.00,74963.00
75%,66888.25,230000.00,16.00,121641.00
max,89184.00,49999999999999992051087350427974655758076739584.00,50.00,74351432.00

In [7]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89184 entries, 0 to 89183
Data columns (total 84 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ResponseId                           89184 non-null  int64
 1   Q120                                 89184 non-null  object
 2   MainBranch                           89184 non-null  object
 3   Age                                  89184 non-null  object
 4   Employment                           87898 non-null  object
 5   RemoteWork                           73810 non-null  object
 6   CodingActivities                     73764 non-null  object
 7   EdLevel                              87973 non-null  object
 8   LearnCode                            87663 non-null  object
 9   LearnCodeOnline                      70084 non-null  object
 10  LearnCodeCoursesCert                 37076 non-null  object
 11  YearsCode                            87435 non-null  object
 12  YearsCodePro                         66136 non-null  object
 13  DevType                              76872 non-null  object
 14  OrgSize                              65043 non-null  object
 15  PurchaseInfluence                    64964 non-null  object
 16  TechList                             60851 non-null  object
 17  BuyNewTool                           83009 non-null  object
 18  Country                              87973 non-null  object
 19  Currency                             65334 non-null  object
 20  CompTotal                            48225 non-null  float64
 21  LanguageHaveWorkedWith               87140 non-null  object
 22  LanguageWantToWorkWith               80709 non-null  object
 23  DatabaseHaveWorkedWith               73435 non-null  object
 24  DatabaseWantToWorkWith               60911 non-null  object
 25  PlatformHaveWorkedWith               63628 non-null  object
 26  PlatformWantToWorkWith               51308 non-null  object
 27  WebframeHaveWorkedWith               66938 non-null  object
 28  WebframeWantToWorkWith               56741 non-null  object
 29  MiscTechHaveWorkedWith               57019 non-null  object
 30  MiscTechWantToWorkWith               46848 non-null  object
 31  ToolsTechHaveWorkedWith              77884 non-null  object
 32  ToolsTechWantToWorkWith              68315 non-null  object
 33  NEWCollabToolsHaveWorkedWith         85864 non-null  object
 34  NEWCollabToolsWantToWorkWith         76649 non-null  object
 35  OpSysPersonal use                    86557 non-null  object
 36  OpSysProfessional use                78587 non-null  object
 37  OfficeStackAsyncHaveWorkedWith       69090 non-null  object
 38  OfficeStackAsyncWantToWorkWith       53743 non-null  object
 39  OfficeStackSyncHaveWorkedWith        83439 non-null  object
 40  OfficeStackSyncWantToWorkWith        69776 non-null  object
 41  AISearchHaveWorkedWith               56328 non-null  object
 42  AISearchWantToWorkWith               46150 non-null  object
 43  AIDevHaveWorkedWith                  25904 non-null  object
 44  AIDevWantToWorkWith                  19587 non-null  object
 45  NEWSOSites                           87973 non-null  object
 46  SOVisitFreq                          87140 non-null  object
 47  SOAccount                            87852 non-null  object
 48  SOPartFreq                           66061 non-null  object
 49  SOComm                               87692 non-null  object
 50  SOAI                                 47912 non-null  object
 51  AISelect                             87973 non-null  object
 52  AISent                               61501 non-null  object
 53  AIAcc                                38594 non-null  object
 54  AIBen                                61396 non-null  object
 55  AIToolInterested in Using            32783 non-null  object
 56  AIToolCurrently Using                36137 non-null  object
 57  AIToolNot interested in Using        21069 non-null  object
 58  AINextVery different                 12661 non-null  object
 59  AINextNeither different nor similar  6599 non-null   object
 60  AINextSomewhat similar               6238 non-null   object
 61  AINextVery similar                   2621 non-null   object
 62  AINextSomewhat different             23303 non-null  object
 63  TBranch                              65768 non-null  object
 64  ICorPM                               43668 non-null  object
 65  WorkExp                              43579 non-null  float64
 66  Knowledge_1                          42535 non-null  object
 67  Knowledge_2                          41670 non-null  object
 68  Knowledge_3                          41798 non-null  object
 69  Knowledge_4                          41684 non-null  object
 70  Knowledge_5                          41527 non-null  object
 71  Knowledge_6                          41520 non-null  object
 72  Knowledge_7                          41467 non-null  object
 73  Knowledge_8                          41404 non-null  object
 74  Frequency_1                          41916 non-null  object
 75  Frequency_2                          41925 non-null  object
 76  Frequency_3                          41054 non-null  object
 77  TimeSearching                        42778 non-null  object
 78  TimeAnswering                        42629 non-null  object
 79  ProfessionalTech                     41783 non-null  object
 80  Industry                             36774 non-null  object
 81  SurveyLength                         86485 non-null  object
 82  SurveyEase                           86554 non-null  object
 83  ConvertedCompYearly                  48019 non-null  float64
dtypes: float64(3), int64(1), object(80)
memory usage: 475.6 MB

#### TODO - 2: - Drop Unnecessary Columns

In [8]:
#Getting list of all the columns
df.columns

Index(['ResponseId', 'Q120', 'MainBranch', 'Age', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType',
       'OrgSize', 'PurchaseInfluence', 'TechList', 'BuyNewTool', 'Country',
       'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysPersonal use',
       'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith',
       'OfficeStackAsyncWantToWorkWith', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'AISearchHaveWorkedWith',
       'AISearchWantToWorkWith', 'AIDevHaveWorkedWith', 'AIDevWantToWorkWith',
       'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq', 'SOComm',
       'SOAI', 'AISelect', 'AISent', 'AIAcc', 'AIBen',
       'AIToolInterested in Using', 'AIToolCurrently Using',
       'AIToolNot interested in Using', 'AINextVery different',
       'AINextNeither different nor similar', 'AINextSomewhat similar',
       'AINextVery similar', 'AINextSomewhat different', 'TBranch', 'ICorPM',
       'WorkExp', 'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4',
       'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Knowledge_8',
       'Frequency_1', 'Frequency_2', 'Frequency_3', 'TimeSearching',
       'TimeAnswering', 'ProfessionalTech', 'Industry', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [9]:
#Selecting columns which need to be dropped from dataframe
drop_col = ['ResponseId', 'Q120', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysPersonal use',
       'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith',
       'OfficeStackAsyncWantToWorkWith', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'AISearchHaveWorkedWith',
       'AISearchWantToWorkWith', 'AIDevHaveWorkedWith', 'AIDevWantToWorkWith',
       'AIToolInterested in Using', 'AIToolCurrently Using',
       'AIToolNot interested in Using', 'AINextVery different',
       'AINextNeither different nor similar', 'AINextSomewhat similar',
       'AINextVery similar', 'AINextSomewhat different', 'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4',
       'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Knowledge_8',
       'Frequency_1', 'Frequency_2', 'Frequency_3', 'SurveyLength',
       'SurveyEase', 'PurchaseInfluence',
       'TechList', 'BuyNewTool','NEWSOSites','SOAI', 'AISelect', 'AISent', 'AIAcc', 'AIBen', 'TBranch']

In [10]:
df.drop(columns=drop_col, axis=1, inplace=True)

In [11]:
df.head(3)

,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,Country,Currency,CompTotal,SOVisitFreq,SOAccount,SOPartFreq,SOComm,ICorPM,WorkExp,TimeSearching,TimeAnswering,ProfessionalTech,Industry,ConvertedCompYearly
0,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Bootstrapping a business;Professional development or self-paced learning from online courses,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;Colleague;Friend or family member;Hackathons (virtual or in-person);Online Courses or Certification;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;Books;Recorded coding sessions;How-to videos;Video-based Online Courses;Written-based Online Courses;Auditory material (e.g., podcasts);Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,United States of America,USD\tUnited States dollar,285000.00,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",People manager,10.00,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testing;Observability tools,"Information Services, IT, Software Development, or other Technology",285000.00
2,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced learning from online courses,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;How-to videos;Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",NaN,27,23,"Developer, back-end","5,000 to 9,999 employees",United States of America,USD\tUnited States dollar,250000.00,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,Individual contributor,23.00,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testing;Observability tools;Innersource initiative;Developer portal or other central places to find tools/services;Continuous integration (CI) and (more often) continuous delivery,"Information Services, IT, Software Development, or other Technology",250000.00

In [12]:
#Final list of columns
df.columns

Index(['MainBranch', 'Age', 'Employment', 'RemoteWork', 'CodingActivities',
       'EdLevel', 'LearnCode', 'LearnCodeOnline', 'LearnCodeCoursesCert',
       'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize', 'Country',
       'Currency', 'CompTotal', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'ICorPM', 'WorkExp', 'TimeSearching', 'TimeAnswering',
       'ProfessionalTech', 'Industry', 'ConvertedCompYearly'],
      dtype='object')

#### TODO - 3: - Handling Missing Values

In [13]:
#Checking for missing values
df.isnull().sum()

MainBranch                  0
Age                         0
Employment               1286
RemoteWork              15374
CodingActivities        15420
EdLevel                  1211
LearnCode                1521
LearnCodeOnline         19100
LearnCodeCoursesCert    52108
YearsCode                1749
YearsCodePro            23048
DevType                 12312
OrgSize                 24141
Country                  1211
Currency                23850
CompTotal               40959
SOVisitFreq              2044
SOAccount                1332
SOPartFreq              23123
SOComm                   1492
ICorPM                  45516
WorkExp                 45605
TimeSearching           46406
TimeAnswering           46555
ProfessionalTech        47401
Industry                52410
ConvertedCompYearly     41165
dtype: int64

Checking the value count of diffrent columns to know how the missing value removal can impact the data

In [14]:
df['Industry'].value_counts()

Information Services, IT, Software Development, or other Technology    18159
Financial Services                                                      4421
Other                                                                   4011
Manufacturing, Transportation, or Supply Chain                          2607
Healthcare                                                              2216
Retail and Consumer Services                                            1955
Higher Education                                                        1242
Advertising Services                                                     786
Insurance                                                                707
Oil & Gas                                                                276
Legal Services                                                           210
Wholesale                                                                184
Name: Industry, dtype: int64

In [15]:
df['MainBranch'].value_counts()

I am a developer by profession                                                           67237
I am not primarily a developer, but I write code sometimes as part of my work/studies     8954
I am learning to code                                                                     4961
I code primarily as a hobby                                                               4960
I used to be a developer by profession, but no longer am                                  1861
None of these                                                                             1211
Name: MainBranch, dtype: int64

In [16]:
df['Age'].value_counts()

25-34 years old       33247
35-44 years old       20532
18-24 years old       17931
45-54 years old        8334
Under 18 years old     4128
55-64 years old        3392
65 years or older      1171
Prefer not to say       449
Name: Age, dtype: int64

In [17]:
df['MainBranch'].isnull().sum()

0

In [18]:
df['RemoteWork'].isnull().sum()

15374

In [19]:
df['RemoteWork'].value_counts()

Hybrid (some remote, some in-person)    31131
Remote                                  30566
In-person                               12113
Name: RemoteWork, dtype: int64

In [20]:
df['EdLevel'].value_counts()

Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          36706
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       20543
Some college/university study without earning a degree                                11753
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     8897
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         3887
Associate degree (A.A., A.S., etc.)                                                    2807
Primary/elementary school                                                              1905
Something else                                                                         1475
Name: EdLevel, dtype: int64

In [21]:
#Removing missing values and saving it into another dataframe
df_na = df.dropna()

In [22]:
df_na.shape

(8580, 27)

In [23]:
df.shape

(89184, 27)

**Post Removing the missing values from data nearly 10% data is left with no missing or null value in any column, hence instead of removing we are replacing na values with 'N/A' and later will be replaced with required values**

In [24]:
new_df = df.fillna('N/A').copy()

In [25]:
new_df.isnull().sum()

MainBranch              0
Age                     0
Employment              0
RemoteWork              0
CodingActivities        0
EdLevel                 0
LearnCode               0
LearnCodeOnline         0
LearnCodeCoursesCert    0
YearsCode               0
YearsCodePro            0
DevType                 0
OrgSize                 0
Country                 0
Currency                0
CompTotal               0
SOVisitFreq             0
SOAccount               0
SOPartFreq              0
SOComm                  0
ICorPM                  0
WorkExp                 0
TimeSearching           0
TimeAnswering           0
ProfessionalTech        0
Industry                0
ConvertedCompYearly     0
dtype: int64

In [26]:
new_df['Industry'].value_counts()

N/A                                                                    52410
Information Services, IT, Software Development, or other Technology    18159
Financial Services                                                      4421
Other                                                                   4011
Manufacturing, Transportation, or Supply Chain                          2607
Healthcare                                                              2216
Retail and Consumer Services                                            1955
Higher Education                                                        1242
Advertising Services                                                     786
Insurance                                                                707
Oil & Gas                                                                276
Legal Services                                                           210
Wholesale                                                                184
Name: Industry, dtype: int64

In [27]:
new_df.head(3)

,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,Country,Currency,CompTotal,SOVisitFreq,SOAccount,SOPartFreq,SOComm,ICorPM,WorkExp,TimeSearching,TimeAnswering,ProfessionalTech,Industry,ConvertedCompYearly
0,None of these,18-24 years old,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
1,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Bootstrapping a business;Professional development or self-paced learning from online courses,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;Colleague;Friend or family member;Hackathons (virtual or in-person);Online Courses or Certification;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;Books;Recorded coding sessions;How-to videos;Video-based Online Courses;Written-based Online Courses;Auditory material (e.g., podcasts);Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,United States of America,USD\tUnited States dollar,285000.00,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",People manager,10.00,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testing;Observability tools,"Information Services, IT, Software Development, or other Technology",285000.00
2,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced learning from online courses,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;How-to videos;Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",N/A,27,23,"Developer, back-end","5,000 to 9,999 employees",United States of America,USD\tUnited States dollar,250000.00,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,Individual contributor,23.00,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testing;Observability tools;Innersource initiative;Developer portal or other central places to find tools/services;Continuous integration (CI) and (more often) continuous delivery,"Information Services, IT, Software Development, or other Technology",250000.00

#### TODO - 4: - Replacing MainBranch columns values to Developer Type values

In [28]:
#Checking for all the unique entry in MainBranch
new_df['MainBranch'].unique()

array(['None of these', 'I am a developer by profession',
       'I am not primarily a developer, but I write code sometimes as part of my work/studies',
       'I code primarily as a hobby', 'I am learning to code',
       'I used to be a developer by profession, but no longer am'],
      dtype=object)

In [29]:
#Replacing the values with new developer type values
new_df['MainBranch'].replace(to_replace =['I am a developer by profession',
                                        'I am not primarily a developer, but I write code sometimes as part of my work/studies',
                                        'I code primarily as a hobby', 'I am learning to code',
                                       'I used to be a developer by profession, but no longer am', 'None of these'],
                           value =['Professional', 'Student', 'Hobby','Learner', 'Ex-Developer', 'None'], inplace=True )

In [30]:
new_df['MainBranch'].value_counts()

Professional    67237
Student          8954
Learner          4961
Hobby            4960
Ex-Developer     1861
None             1211
Name: MainBranch, dtype: int64

In [31]:
#Checking for the data post applying changes
new_df.head(2)

,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,Country,Currency,CompTotal,SOVisitFreq,SOAccount,SOPartFreq,SOComm,ICorPM,WorkExp,TimeSearching,TimeAnswering,ProfessionalTech,Industry,ConvertedCompYearly
0,None,18-24 years old,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
1,Professional,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Bootstrapping a business;Professional development or self-paced learning from online courses,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;Colleague;Friend or family member;Hackathons (virtual or in-person);Online Courses or Certification;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;Books;Recorded coding sessions;How-to videos;Video-based Online Courses;Written-based Online Courses;Auditory material (e.g., podcasts);Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,United States of America,USD\tUnited States dollar,285000.00,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",People manager,10.00,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testing;Observability tools,"Information Services, IT, Software Development, or other Technology",285000.00

#### TODO - 5: - Replacing values of Age Columns

In [32]:
#Checking for all the unique age in the column
new_df['Age'].unique()

array(['18-24 years old', '25-34 years old', '45-54 years old',
       '35-44 years old', 'Under 18 years old', '55-64 years old',
       '65 years or older', 'Prefer not to say'], dtype=object)

In [33]:
new_df['Age'].replace(to_replace =['18-24 years old', '25-34 years old', '45-54 years old',
       '35-44 years old', 'Under 18 years old', '55-64 years old',
       '65 years or older', 'Prefer not to say'],
                           value =['18-24', '25-34', '45-54','35-44', 'under 18', '55-64', 'over 65', 'Not Disclosed'], inplace=True )

In [34]:
new_df.head(3)

,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,Country,Currency,CompTotal,SOVisitFreq,SOAccount,SOPartFreq,SOComm,ICorPM,WorkExp,TimeSearching,TimeAnswering,ProfessionalTech,Industry,ConvertedCompYearly
0,None,18-24,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
1,Professional,25-34,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Bootstrapping a business;Professional development or self-paced learning from online courses,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;Colleague;Friend or family member;Hackathons (virtual or in-person);Online Courses or Certification;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;Books;Recorded coding sessions;How-to videos;Video-based Online Courses;Written-based Online Courses;Auditory material (e.g., podcasts);Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,United States of America,USD\tUnited States dollar,285000.00,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",People manager,10.00,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testing;Observability tools,"Information Services, IT, Software Development, or other Technology",285000.00
2,Professional,45-54,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced learning from online courses,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;How-to videos;Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",N/A,27,23,"Developer, back-end","5,000 to 9,999 employees",United States of America,USD\tUnited States dollar,250000.00,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,Individual contributor,23.00,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testing;Observability tools;Innersource initiative;Developer portal or other central places to find tools/services;Continuous integration (CI) and (more often) continuous delivery,"Information Services, IT, Software Development, or other Technology",250000.00

#### TODO - 5: - Editing Employement Type, Education Type and Organization Size columns value

In [35]:
new_df['Employment'].unique()

array(['N/A', 'Employed, full-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed',
       'Not employed, but looking for work',
       'Independent contractor, freelancer, or self-employed',
       'Student, full-time',
       'Independent contractor, freelancer, or self-employed;Employed, part-time;Student, part-time',
       'Not employed, but looking for work;Student, full-time',
       'Employed, part-time;Student, part-time', 'Employed, part-time',
       'Student, full-time;Employed, part-time', 'I prefer not to say',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Employed, full-time;Student, part-time',
       'Not employed, but looking for work;Employed, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time',
       'Retired', 'Employed, full-time;Student, full-time',
       'Student, full-time;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Student, full-time',
       'Not employed, and not looking for work', 'Student, part-time',
       'Student, full-time;Not employed, and not looking for work',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, but looking for work',
       'Employed, full-time;Employed, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Not employed, and not looking for work',
       'Independent contractor, freelancer, or self-employed;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Not employed, and not looking for work',
       'Student, full-time;Employed, part-time;Not employed, and not looking for work',
       'Not employed, but looking for work;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work',
       'Independent contractor, freelancer, or self-employed;Student, full-time;Employed, part-time',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Student, full-time',
       'Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Employed, full-time;Employed, part-time;Student, part-time',
       'Not employed, but looking for work;Student, full-time;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Employed, part-time',
       'Student, part-time;Not employed, and not looking for work',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, full-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Employed, part-time;Retired',
       'Not employed, but looking for work;Not employed, and not looking for work',
       'Retired;Not employed, and not looking for work',
       'Independent contractor, freelancer, or self-employed;Retired',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Not employed, and not looking for work',
       'Employed, full-time;Student, full-time;Employed, part-time',
       'Independent contractor, freelancer, or self-employed;Student, full-time;Not employed, and not looking for work',
       'Employed, full-time;Not employed, but looking for work',
       'Not employed, but looking for work;Employed, part-time;Student, part-time',
       'Student, full-time;Employed, part-time;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Student, part-time;Not employed, and not looking for work',
       'Independent contractor, freelancer, or self-employed;Student, full-time;Employed, part-time;Student, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, full-time;Retired',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Student, full-time;Employed, part-time;Student, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, full-time;Student, part-time',
       'Employed, full-time;Not employed, and not looking for work',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, full-time;Employed, part-time;Student, part-time',
       'Not employed, but looking for work;Student, full-time;Not employed, and not looking for work',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Employed, part-time',
       'Employed, full-time;Not employed, but looking for work;Student, full-time;Student, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, full-time;Employed, part-time',
       'Not employed, but looking for work;Student, full-time;Employed, part-time',
       'Employed, full-time;Not employed, but looking for work;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Student, part-time;Retired',
       'Employed, part-time;Student, part-time;Retired',
       'Employed, full-time;Retired', 'Employed, part-time;Retired',
       'Employed, full-time;Not employed, but looking for work;Student, full-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Student, full-time;Employed, part-time;Student, part-time;Not employed, and not looking for work',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Retired',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Employed, part-time;Student, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, full-time;Not employed, and not looking for work',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Student, full-time;Employed, part-time',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Employed, part-time;Not employed, and not looking for work',
       'Student, full-time;Retired',
       'Employed, full-time;Student, full-time;Employed, part-time;Student, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Retired',
       'Not employed, but looking for work;Student, full-time;Student, part-time;Not employed, and not looking for work',
       'Student, full-time;Student, part-time;Not employed, and not looking for work',
       'Not employed, but looking for work;Retired',
       'Employed, full-time;Student, full-time;Retired',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Student, part-time;Retired',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Student, full-time;Not employed, and not looking for work',
       'Independent contractor, freelancer, or self-employed;Retired;Not employed, and not looking for work',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Student, full-time;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Student, full-time;Student, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Employed, part-time;Not employed, and not looking for work',
       'Independent contractor, freelancer, or self-employed;Student, full-time;Retired',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Student, full-time;Employed, part-time;Student, part-time;Retired;Not employed, and not looking for work',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Student, full-time;Student, part-time',
       'Employed, part-time;Not employed, and not looking for work',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Retired',
       'Employed, full-time;Student, part-time;Retired',
       'Employed, full-time;Not employed, but looking for work;Employed, part-time',
       'Not employed, but looking for work;Student, part-time;Not employed, and not looking for work',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Student, full-time;Student, part-time;Not employed, and not looking for work',
       'Employed, full-time;Student, full-time;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Student, full-time;Employed, part-time;Not employed, and not looking for work',
       'Employed, full-time;Student, full-time;Not employed, and not looking for work',
       'Not employed, but looking for work;Student, full-time;Employed, part-time;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Student, full-time;Student, part-time;Not employed, and not looking for work',
       'Employed, full-time;Student, full-time;Employed, part-time;Student, part-time;Not employed, and not looking for work',
       'Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Employed, part-time;Retired',
       'Employed, full-time;Not employed, but looking for work;Student, full-time;Employed, part-time;Student, part-time',
       'Employed, full-time;Not employed, but looking for work;Employed, part-time;Student, part-time'],
      dtype=object)

`employment(string)` function take the string as input and check for keywords and return the employment type based on the keyword

In [36]:
#Function to get the employment type
def employment(string):
    if 'Employed, full-time' in string:
        return 'Employed, full-time'
    elif 'Employed, part-time' in string:
        return 'Employed, part-time'
    elif 'Independent contractor, freelancer, or self-employed' in string:
        return 'Independent contractor, freelancer, or self-employed'
    elif 'Not employed, but looking for work' in string:
        return 'Not employed, but looking for work'
    elif 'Not employed, and not looking for work' in string:
        return 'Not employed, and not looking for work'
    elif 'Student, full-time' in string:
        return 'Student, full-time'
    elif 'Student, part-time' in string:
        return 'Student, part-time'
    elif 'Retired' in string:
        return 'Retired'
    else:
        return 'Not Disclosed'

In [37]:
new_df['Employment'] = new_df['Employment'].apply(employment)

In [38]:
new_df.head(3)

,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,Country,Currency,CompTotal,SOVisitFreq,SOAccount,SOPartFreq,SOComm,ICorPM,WorkExp,TimeSearching,TimeAnswering,ProfessionalTech,Industry,ConvertedCompYearly
0,None,18-24,Not Disclosed,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
1,Professional,25-34,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Bootstrapping a business;Professional development or self-paced learning from online courses,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;Colleague;Friend or family member;Hackathons (virtual or in-person);Online Courses or Certification;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;Books;Recorded coding sessions;How-to videos;Video-based Online Courses;Written-based Online Courses;Auditory material (e.g., podcasts);Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,United States of America,USD\tUnited States dollar,285000.00,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",People manager,10.00,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testing;Observability tools,"Information Services, IT, Software Development, or other Technology",285000.00
2,Professional,45-54,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced learning from online courses,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;How-to videos;Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",N/A,27,23,"Developer, back-end","5,000 to 9,999 employees",United States of America,USD\tUnited States dollar,250000.00,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,Individual contributor,23.00,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testing;Observability tools;Innersource initiative;Developer portal or other central places to find tools/services;Continuous integration (CI) and (more often) continuous delivery,"Information Services, IT, Software Development, or other Technology",250000.00

In [39]:
#Checking all eduction level values
new_df['EdLevel'].value_counts()

Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          36706
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       20543
Some college/university study without earning a degree                                11753
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     8897
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         3887
Associate degree (A.A., A.S., etc.)                                                    2807
Primary/elementary school                                                              1905
Something else                                                                         1475
N/A                                                                                    1211
Name: EdLevel, dtype: int64

In [40]:
#Replacing the old values with the simple ones
new_df['EdLevel'].replace(to_replace=['Bachelor’s degree (B.A., B.S., B.Eng., etc.)', 'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)', 'Some college/university study without earning a degree', 'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)', 'Professional degree (JD, MD, Ph.D, Ed.D, etc.)', 'Associate degree (A.A., A.S., etc.)', 'Primary/elementary school'], 
                        value=["Bachelor's Degree", "Master's Degree", "College but no degree", "Secondary School", "Professional Degree", "Associate Degree", "Primary School"], inplace=True)

In [41]:
new_df.head(3)

,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,Country,Currency,CompTotal,SOVisitFreq,SOAccount,SOPartFreq,SOComm,ICorPM,WorkExp,TimeSearching,TimeAnswering,ProfessionalTech,Industry,ConvertedCompYearly
0,None,18-24,Not Disclosed,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
1,Professional,25-34,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Bootstrapping a business;Professional development or self-paced learning from online courses,Bachelor's Degree,"Books / Physical media;Colleague;Friend or family member;Hackathons (virtual or in-person);Online Courses or Certification;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;Books;Recorded coding sessions;How-to videos;Video-based Online Courses;Written-based Online Courses;Auditory material (e.g., podcasts);Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,United States of America,USD\tUnited States dollar,285000.00,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",People manager,10.00,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testing;Observability tools,"Information Services, IT, Software Development, or other Technology",285000.00
2,Professional,45-54,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced learning from online courses,Bachelor's Degree,"Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;How-to videos;Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",N/A,27,23,"Developer, back-end","5,000 to 9,999 employees",United States of America,USD\tUnited States dollar,250000.00,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,Individual contributor,23.00,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testing;Observability tools;Innersource initiative;Developer portal or other central places to find tools/services;Continuous integration (CI) and (more often) continuous delivery,"Information Services, IT, Software Development, or other Technology",250000.00

In [42]:
#Unique values of Organization size column
new_df['OrgSize'].value_counts()

N/A                                                   24141
20 to 99 employees                                    13380
100 to 499 employees                                  12218
10,000 or more employees                               7929
1,000 to 4,999 employees                               7235
2 to 9 employees                                       6439
10 to 19 employees                                     5254
500 to 999 employees                                   4472
Just me - I am a freelancer, sole proprietor, etc.     4196
5,000 to 9,999 employees                               2677
I don’t know                                           1243
Name: OrgSize, dtype: int64

In [43]:
#Replacing them with the new and simple values
new_df['OrgSize'].replace(to_replace=['20 to 99 employees', '100 to 499 employees', '10,000 or more employees', '1,000 to 4,999 employees', '2 to 9 employees', '10 to 19 employees', '500 to 999 employees', 'Just me - I am a freelancer, sole proprietor, etc.', '5,000 to 9,999 employees', 'I don’t know' ], 
                        value=["20-99", "100-499", "10000 or more", "1K-4999", "2-9", "10-19", "500-999", 'Freelancer', '5K-9999','Unknown'], inplace=True)

In [44]:
new_df.head(3)

,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,Country,Currency,CompTotal,SOVisitFreq,SOAccount,SOPartFreq,SOComm,ICorPM,WorkExp,TimeSearching,TimeAnswering,ProfessionalTech,Industry,ConvertedCompYearly
0,None,18-24,Not Disclosed,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
1,Professional,25-34,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Bootstrapping a business;Professional development or self-paced learning from online courses,Bachelor's Degree,"Books / Physical media;Colleague;Friend or family member;Hackathons (virtual or in-person);Online Courses or Certification;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;Books;Recorded coding sessions;How-to videos;Video-based Online Courses;Written-based Online Courses;Auditory material (e.g., podcasts);Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2-9,United States of America,USD\tUnited States dollar,285000.00,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",People manager,10.00,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testing;Observability tools,"Information Services, IT, Software Development, or other Technology",285000.00
2,Professional,45-54,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced learning from online courses,Bachelor's Degree,"Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;How-to videos;Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",N/A,27,23,"Developer, back-end",5K-9999,United States of America,USD\tUnited States dollar,250000.00,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,Individual contributor,23.00,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testing;Observability tools;Innersource initiative;Developer portal or other central places to find tools/services;Continuous integration (CI) and (more often) continuous delivery,"Information Services, IT, Software Development, or other Technology",250000.00

#### TODO - 6: - Changing Learncode column to Mode of Learning

In [45]:
new_df['LearnCode'].unique()[:10]

array(['N/A',
       'Books / Physical media;Colleague;Friend or family member;Hackathons (virtual or in-person);Online Courses or Certification;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)',
       'Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)',
       'Colleague;Friend or family member;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)',
       'Books / Physical media;Online Courses or Certification;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)',
       'Books / Physical media;Colleague;Online Courses or Certification;Other online resources (e.g., videos, blogs, forum)',
       'Friend or family member;Online Courses or Certification;Coding Bootcamp',
       'Books / Physical media;Online Courses or Certification;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc);Coding Bootcamp',
       'Online Courses or Certification;On the job training;Other online resources (e.g., videos, blogs, forum)',
       'Books / Physical media;Online Courses or Certification;Other online resources (e.g., videos, blogs, forum)'],
      dtype=object)

`learning(string)` function to get the learning source of coding. Function take string as input which is number of diffrent options based on that we can get the most useful or common source of learning

In [46]:
#Function to get leanring source of code
def learning(string):
    if 'Books / Physical media' in string:
        return 'Books / Physical media'
    elif 'Coding Bootcamp' in string:
        return 'Coding Bootcamp'
    elif 'Colleague' in string:
        return 'Colleague'
    elif 'Friend or family member' in string:
        return 'Friend or family member'
    elif 'Hackathons' in string:
        return 'Hackathons'
    elif 'Online Courses or Certification' in string:
        return 'Online Courses or Certification'
    elif 'On the job training' in string:
        return 'Job training'
    elif 'Other online resources (e.g., videos, blogs, forum)' in string:
        return 'Other online resources (e.g., videos, blogs, forum)'
    elif 'School (i.e., University, College, etc)' in string:
        return 'School or College'
    else:
        return 'Other'

In [47]:
#Saving data into the same column
new_df['Learning Source'] = new_df['LearnCode'].apply(learning)

In [48]:
new_df.head(3)

,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,Country,Currency,CompTotal,SOVisitFreq,SOAccount,SOPartFreq,SOComm,ICorPM,WorkExp,TimeSearching,TimeAnswering,ProfessionalTech,Industry,ConvertedCompYearly,Learning Source
0,None,18-24,Not Disclosed,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Other
1,Professional,25-34,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Bootstrapping a business;Professional development or self-paced learning from online courses,Bachelor's Degree,"Books / Physical media;Colleague;Friend or family member;Hackathons (virtual or in-person);Online Courses or Certification;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;Books;Recorded coding sessions;How-to videos;Video-based Online Courses;Written-based Online Courses;Auditory material (e.g., podcasts);Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2-9,United States of America,USD\tUnited States dollar,285000.00,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",People manager,10.00,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testing;Observability tools,"Information Services, IT, Software Development, or other Technology",285000.00,Books / Physical media
2,Professional,45-54,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced learning from online courses,Bachelor's Degree,"Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;How-to videos;Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",N/A,27,23,"Developer, back-end",5K-9999,United States of America,USD\tUnited States dollar,250000.00,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,Individual contributor,23.00,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testing;Observability tools;Innersource initiative;Developer portal or other central places to find tools/services;Continuous integration (CI) and (more often) continuous delivery,"Information Services, IT, Software Development, or other Technology",250000.00,Books / Physical media

#### TODO - 7: - Rename columns

In [49]:
# Dictionary of columns whose name need to changed
col1 = {'MainBranch': 'Developer Type', 
        'DevType':'Job Role',
        'EdLevel': 'Education Level',
        'YearsCode': 'Total Coding Experience',
        'YearsCodePro': 'Professional Coding Exp',
        'OrgSize': 'Organization Size',
        'WorkExp': 'Work Experience',
        'ConvertedCompYearly': 'Income in $'
       }

In [50]:
new_df.rename(columns=col1, inplace=True)

In [51]:
new_df.head(3)

,Developer Type,Age,Employment,RemoteWork,CodingActivities,Education Level,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,Total Coding Experience,Professional Coding Exp,Job Role,Organization Size,Country,Currency,CompTotal,SOVisitFreq,SOAccount,SOPartFreq,SOComm,ICorPM,Work Experience,TimeSearching,TimeAnswering,ProfessionalTech,Industry,Income in $,Learning Source
0,None,18-24,Not Disclosed,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Other
1,Professional,25-34,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Bootstrapping a business;Professional development or self-paced learning from online courses,Bachelor's Degree,"Books / Physical media;Colleague;Friend or family member;Hackathons (virtual or in-person);Online Courses or Certification;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;Books;Recorded coding sessions;How-to videos;Video-based Online Courses;Written-based Online Courses;Auditory material (e.g., podcasts);Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2-9,United States of America,USD\tUnited States dollar,285000.00,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",People manager,10.00,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testing;Observability tools,"Information Services, IT, Software Development, or other Technology",285000.00,Books / Physical media
2,Professional,45-54,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced learning from online courses,Bachelor's Degree,"Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc)","Formal documentation provided by the owner of the tech;Blogs with tips and tricks;How-to videos;Online challenges (e.g., daily or weekly coding challenges);Written Tutorials;Click to write Choice 20;Stack Overflow",N/A,27,23,"Developer, back-end",5K-9999,United States of America,USD\tUnited States dollar,250000.00,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,Individual contributor,23.00,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testing;Observability tools;Innersource initiative;Developer portal or other central places to find tools/services;Continuous integration (CI) and (more often) continuous delivery,"Information Services, IT, Software Development, or other Technology",250000.00,Books / Physical media

**The Dataframe have many columns which can used to analyse the use of stackoverflow by the users, how often they use, how often they find the answers of their query etc. For now we are focusing on the users profile, hence making a copy of data and creating new dataframe for further analysis.**

In [52]:
stack_data = new_df.copy()

In [53]:
new_df.columns

Index(['Developer Type', 'Age', 'Employment', 'RemoteWork', 'CodingActivities',
       'Education Level', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'Total Coding Experience',
       'Professional Coding Exp', 'Job Role', 'Organization Size', 'Country',
       'Currency', 'CompTotal', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'ICorPM', 'Work Experience', 'TimeSearching', 'TimeAnswering',
       'ProfessionalTech', 'Industry', 'Income in $', 'Learning Source'],
      dtype='object')

In [54]:
#List of columns which needed for further analysis
required_col = ['Developer Type', 'Age', 'Employment', 'Job Role', 'Organization Size', 'Country', 'Work Experience', 'Industry','Total Coding Experience', 'Professional Coding Exp', 'RemoteWork', 'Education Level', 'Learning Source', 'Income in $']

final_df = new_df[required_col].copy()

In [55]:
final_df.head(3)

,Developer Type,Age,Employment,Job Role,Organization Size,Country,Work Experience,Industry,Total Coding Experience,Professional Coding Exp,RemoteWork,Education Level,Learning Source,Income in $
0,None,18-24,Not Disclosed,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,Other,N/A
1,Professional,25-34,"Employed, full-time","Senior Executive (C-Suite, VP, etc.)",2-9,United States of America,10.00,"Information Services, IT, Software Development, or other Technology",18,9,Remote,Bachelor's Degree,Books / Physical media,285000.00
2,Professional,45-54,"Employed, full-time","Developer, back-end",5K-9999,United States of America,23.00,"Information Services, IT, Software Development, or other Technology",27,23,"Hybrid (some remote, some in-person)",Bachelor's Degree,Books / Physical media,250000.00

In [56]:
final_df.columns = [item.replace(" ", '_') for item in final_df.columns]

In [57]:
final_df.columns

Index(['Developer_Type', 'Age', 'Employment', 'Job_Role', 'Organization_Size',
       'Country', 'Work_Experience', 'Industry', 'Total_Coding_Experience',
       'Professional_Coding_Exp', 'RemoteWork', 'Education_Level',
       'Learning_Source', 'Income_in_$'],
      dtype='object')

In [58]:
#Dropping all unwanted rows from data
drop_index = final_df.query('Developer_Type == "None" | Professional_Coding_Exp == "N/A" ').index

In [59]:
final_df.drop(index=drop_index, inplace=True)

In [60]:
final_df.head(3)

,Developer_Type,Age,Employment,Job_Role,Organization_Size,Country,Work_Experience,Industry,Total_Coding_Experience,Professional_Coding_Exp,RemoteWork,Education_Level,Learning_Source,Income_in_$
1,Professional,25-34,"Employed, full-time","Senior Executive (C-Suite, VP, etc.)",2-9,United States of America,10.00,"Information Services, IT, Software Development, or other Technology",18,9,Remote,Bachelor's Degree,Books / Physical media,285000.00
2,Professional,45-54,"Employed, full-time","Developer, back-end",5K-9999,United States of America,23.00,"Information Services, IT, Software Development, or other Technology",27,23,"Hybrid (some remote, some in-person)",Bachelor's Degree,Books / Physical media,250000.00
3,Professional,25-34,"Employed, full-time","Developer, front-end",100-499,United States of America,7.00,N/A,12,7,"Hybrid (some remote, some in-person)",Bachelor's Degree,Colleague,156000.00

In [61]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 66136 entries, 1 to 89183
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Developer_Type           66136 non-null  object
 1   Age                      66136 non-null  object
 2   Employment               66136 non-null  object
 3   Job_Role                 66136 non-null  object
 4   Organization_Size        66136 non-null  object
 5   Country                  66136 non-null  object
 6   Work_Experience          66136 non-null  object
 7   Industry                 66136 non-null  object
 8   Total_Coding_Experience  66136 non-null  object
 9   Professional_Coding_Exp  66136 non-null  object
 10  RemoteWork               66136 non-null  object
 11  Education_Level          66136 non-null  object
 12  Learning_Source          66136 non-null  object
 13  Income_in_$              66136 non-null  object
dtypes: object(14)
memory usage: 7.6+ MB

In [62]:
final_df.describe()

,Developer_Type,Age,Employment,Job_Role,Organization_Size,Country,Work_Experience,Industry,Total_Coding_Experience,Professional_Coding_Exp,RemoteWork,Education_Level,Learning_Source,Income_in_$
count,66136,66136,66136,66136,66136,66136,66136,66136,66136,66136,66136,66136,66136,66136
unique,3,8,5,34,11,180,52,13,53,52,4,8,10,8758
top,Professional,25-34,"Employed, full-time","Developer, full-stack",20-99,United States of America,N/A,N/A,10,5,"Hybrid (some remote, some in-person)",Bachelor's Degree,Books / Physical media,N/A
freq,59053,28644,57016,22809,13309,14901,24917,31287,5306,4792,27794,30476,36198,18311

#### TODO - 8: - Create Label Bins for Work Experience and Professional Coding Experience Column

In [63]:
#Checking for Work Experience column
final_df['Work_Experience'].value_counts()

N/A     24917
5.0      3081
10.0     2899
3.0      2508
2.0      2467
4.0      2331
7.0      2325
6.0      2195
8.0      2155
15.0     1937
1.0      1930
12.0     1682
20.0     1555
9.0      1378
11.0     1284
25.0     1175
13.0     1136
16.0      855
17.0      837
14.0      828
18.0      755
23.0      720
30.0      610
22.0      529
24.0      405
19.0      373
21.0      369
26.0      326
27.0      291
35.0      283
28.0      262
0.0       182
40.0      173
33.0      167
32.0      161
29.0      127
31.0      127
36.0      123
34.0      105
37.0       88
38.0       85
41.0       67
50.0       67
45.0       51
39.0       45
42.0       44
43.0       41
44.0       27
46.0       26
47.0       17
48.0       11
49.0        4
Name: Work_Experience, dtype: int64

In [64]:
final_df[final_df['Work_Experience'] == 'N/A']

,Developer_Type,Age,Employment,Job_Role,Organization_Size,Country,Work_Experience,Industry,Total_Coding_Experience,Professional_Coding_Exp,RemoteWork,Education_Level,Learning_Source,Income_in_$
8,Student,45-54,"Employed, full-time",System administrator,100-499,Finland,N/A,N/A,20,15,"Hybrid (some remote, some in-person)",Master's Degree,Online Courses or Certification,64254.00
11,Professional,25-34,"Employed, full-time","Developer, full-stack",100-499,Australia,N/A,N/A,10,9,Remote,Bachelor's Degree,Online Courses or Certification,78003.00
16,Professional,35-44,"Employed, full-time","Developer, front-end",1K-4999,Sweden,N/A,N/A,4,2,"Hybrid (some remote, some in-person)",Bachelor's Degree,Coding Bootcamp,45149.00
22,Professional,25-34,"Employed, full-time","Developer, full-stack",20-99,Nigeria,N/A,N/A,8,6,Remote,Bachelor's Degree,Books / Physical media,120000.00
23,Student,25-34,"Employed, full-time",Data or business analyst,500-999,Germany,N/A,N/A,13,10,Remote,Professional Degree,Colleague,69608.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89146,Professional,18-24,"Employed, part-time","Developer, full-stack",Freelancer,Germany,N/A,N/A,12,6,"Hybrid (some remote, some in-person)",Something else,Online Courses or Certification,1606.00
89155,Professional,25-34,"Employed, full-time","Developer, full-stack",20-99,Canada,N/A,N/A,1,Less than 1 year,Remote,College but no degree,Coding Bootcamp,63199.00
89158,Professional,25-34,"Employed, full-time","Developer, front-end",100-499,Sweden,N/A,N/A,11,8,"Hybrid (some remote, some in-person)",Bachelor's Degree,Colleague,52981.00
89161,Professional,25-34,"Employed, full-time","Engineer, data",10000 or more,China,N/A,N/A,12,6,In-person,Master's Degree,Books / Physical media,N/A
89179,Professional,25-34,"Employed, full-time","Developer, front-end",100-499,Brazil,N/A,N/A,20,5,Remote,Associate Degree,Online Courses or Certification,N/A

In [65]:
#Replacing 'N/A' values with 0, considering users with no work experience
final_df['Work_Experience'].replace('N/A', 0, inplace=True)

In [66]:
final_df.head()

,Developer_Type,Age,Employment,Job_Role,Organization_Size,Country,Work_Experience,Industry,Total_Coding_Experience,Professional_Coding_Exp,RemoteWork,Education_Level,Learning_Source,Income_in_$
1,Professional,25-34,"Employed, full-time","Senior Executive (C-Suite, VP, etc.)",2-9,United States of America,10.00,"Information Services, IT, Software Development, or other Technology",18,9,Remote,Bachelor's Degree,Books / Physical media,285000.00
2,Professional,45-54,"Employed, full-time","Developer, back-end",5K-9999,United States of America,23.00,"Information Services, IT, Software Development, or other Technology",27,23,"Hybrid (some remote, some in-person)",Bachelor's Degree,Books / Physical media,250000.00
3,Professional,25-34,"Employed, full-time","Developer, front-end",100-499,United States of America,7.00,N/A,12,7,"Hybrid (some remote, some in-person)",Bachelor's Degree,Colleague,156000.00
4,Professional,25-34,"Employed, full-time","Developer, full-stack",20-99,Philippines,6.00,Other,6,4,Remote,Bachelor's Degree,Books / Physical media,23456.00
5,Professional,35-44,"Employed, full-time","Developer, back-end",100-499,United Kingdom of Great Britain and Northern Ireland,22.00,Other,21,21,Remote,College but no degree,Books / Physical media,96828.00

In [67]:
final_df.loc[:,'Work_Experience'].value_counts()

0.00     25099
5.00      3081
10.00     2899
3.00      2508
2.00      2467
4.00      2331
7.00      2325
6.00      2195
8.00      2155
15.00     1937
1.00      1930
12.00     1682
20.00     1555
9.00      1378
11.00     1284
25.00     1175
13.00     1136
16.00      855
17.00      837
14.00      828
18.00      755
23.00      720
30.00      610
22.00      529
24.00      405
19.00      373
21.00      369
26.00      326
27.00      291
35.00      283
28.00      262
40.00      173
33.00      167
32.00      161
31.00      127
29.00      127
36.00      123
34.00      105
37.00       88
38.00       85
50.00       67
41.00       67
45.00       51
39.00       45
42.00       44
43.00       41
44.00       27
46.00       26
47.00       17
48.00       11
49.00        4
Name: Work_Experience, dtype: int64

In [68]:
#Using pandas cut method to create bins and save the values in 'Work Experience Group' column
final_df['Work_Experience_Group'] = pd.cut(final_df['Work_Experience'], [0,5,15,25,35,50], labels=['0-5', '6-15', '16-25', '26-35', '36-50'])

In [69]:
final_df['Work_Experience_Group'].value_counts()

6-15     17819
0-5      12317
16-25     7573
26-35     2459
36-50      869
Name: Work_Experience_Group, dtype: int64

In [70]:
final_df.head(3)

,Developer_Type,Age,Employment,Job_Role,Organization_Size,Country,Work_Experience,Industry,Total_Coding_Experience,Professional_Coding_Exp,RemoteWork,Education_Level,Learning_Source,Income_in_$,Work_Experience_Group
1,Professional,25-34,"Employed, full-time","Senior Executive (C-Suite, VP, etc.)",2-9,United States of America,10.00,"Information Services, IT, Software Development, or other Technology",18,9,Remote,Bachelor's Degree,Books / Physical media,285000.00,6-15
2,Professional,45-54,"Employed, full-time","Developer, back-end",5K-9999,United States of America,23.00,"Information Services, IT, Software Development, or other Technology",27,23,"Hybrid (some remote, some in-person)",Bachelor's Degree,Books / Physical media,250000.00,16-25
3,Professional,25-34,"Employed, full-time","Developer, front-end",100-499,United States of America,7.00,N/A,12,7,"Hybrid (some remote, some in-person)",Bachelor's Degree,Colleague,156000.00,6-15

In [71]:
#Checking for Coding experience group
final_df['Professional_Coding_Exp'].value_counts()

5                     4792
10                    4594
2                     4464
3                     4378
4                     3970
6                     3637
7                     3509
8                     3462
15                    2789
1                     2596
12                    2398
20                    2227
9                     2145
11                    2013
Less than 1 year      1836
13                    1690
25                    1449
16                    1278
14                    1256
18                    1212
17                    1146
23                    1112
30                     924
22                     845
24                     686
19                     649
21                     565
27                     490
26                     486
35                     462
28                     417
40                     329
32                     293
33                     264
29                     217
36                     200
31                     187
34                     177
38                     164
37                     150
45                     102
39                      99
More than 50 years      83
42                      81
41                      79
43                      67
44                      42
46                      33
48                      30
47                      24
50                      24
49                      14
Name: Professional_Coding_Exp, dtype: int64

**`['Less than 1 year', 'More than 50 years']` will be converted into 0.5 and 50 to make the calculation easy**

In [72]:
#Replacing string values from column to convert them into numerical value
final_df['Professional_Coding_Exp'].replace(to_replace = ['Less than 1 year', 'More than 50 years'], value=[0.5, 50], inplace=True)

In [73]:
final_df['Professional_Coding_Exp'] = final_df['Professional_Coding_Exp'].astype('float64')

In [74]:
#Using pandas cut method to create bins and save the values in 'Professional_Coding_Exp_Group' column
final_df['Professional_Coding_Exp_Group'] = pd.cut(final_df['Professional_Coding_Exp'], [0.5,5,15,25,35,50], labels=['0-5', '6-15', '16-25', '26-35', '36-50'])

In [75]:
final_df['Professional_Coding_Exp_Group'].value_counts()

6-15     27493
0-5      20200
16-25    11169
26-35     3917
36-50     1521
Name: Professional_Coding_Exp_Group, dtype: int64

In [76]:
final_df['Industry'].value_counts()

N/A                                                                    31287
Information Services, IT, Software Development, or other Technology    17279
Financial Services                                                      4224
Other                                                                   3779
Manufacturing, Transportation, or Supply Chain                          2444
Healthcare                                                              2115
Retail and Consumer Services                                            1863
Higher Education                                                        1091
Advertising Services                                                     748
Insurance                                                                682
Oil & Gas                                                                251
Legal Services                                                           196
Wholesale                                                                177
Name: Industry, dtype: int64

In [77]:
#Replacing N/A with 0, considering people with no job
final_df['Income_in_$'].replace('N/A', 0, inplace=True)

In [78]:
final_df.describe()

       Work_Experience  Professional_Coding_Exp  Income_in_$
count         66136.00                 66136.00     66136.00
mean              7.27                    11.25     74588.44
std               9.12                     9.22    582408.32
min               0.00                     0.50         0.00
25%               0.00                     4.00         0.00
50%               4.00                     9.00     51681.00
75%              11.00                    16.00    100000.00
max              50.00                    50.00  74351432.00

In [79]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 66136 entries, 1 to 89183
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Developer_Type                 66136 non-null  object
 1   Age                            66136 non-null  object
 2   Employment                     66136 non-null  object
 3   Job_Role                       66136 non-null  object
 4   Organization_Size              66136 non-null  object
 5   Country                        66136 non-null  object
 6   Work_Experience                66136 non-null  float64
 7   Industry                       66136 non-null  object
 8   Total_Coding_Experience        66136 non-null  object
 9   Professional_Coding_Exp        66136 non-null  float64
 10  RemoteWork                     66136 non-null  object
 11  Education_Level                66136 non-null  object
 12  Learning_Source                66136 non-null  object
 13  Income_in_$                    66136 non-null  float64
 14  Work_Experience_Group          41037 non-null  category
 15  Professional_Coding_Exp_Group  64300 non-null  category
dtypes: category(2), float64(3), object(11)
memory usage: 7.7+ MB

In [80]:
#Final DataFrame
final_df.head()

,Developer_Type,Age,Employment,Job_Role,Organization_Size,Country,Work_Experience,Industry,Total_Coding_Experience,Professional_Coding_Exp,RemoteWork,Education_Level,Learning_Source,Income_in_$,Work_Experience_Group,Professional_Coding_Exp_Group
1,Professional,25-34,"Employed, full-time","Senior Executive (C-Suite, VP, etc.)",2-9,United States of America,10.00,"Information Services, IT, Software Development, or other Technology",18,9.00,Remote,Bachelor's Degree,Books / Physical media,285000.00,6-15,6-15
2,Professional,45-54,"Employed, full-time","Developer, back-end",5K-9999,United States of America,23.00,"Information Services, IT, Software Development, or other Technology",27,23.00,"Hybrid (some remote, some in-person)",Bachelor's Degree,Books / Physical media,250000.00,16-25,16-25
3,Professional,25-34,"Employed, full-time","Developer, front-end",100-499,United States of America,7.00,N/A,12,7.00,"Hybrid (some remote, some in-person)",Bachelor's Degree,Colleague,156000.00,6-15,6-15
4,Professional,25-34,"Employed, full-time","Developer, full-stack",20-99,Philippines,6.00,Other,6,4.00,Remote,Bachelor's Degree,Books / Physical media,23456.00,6-15,0-5
5,Professional,35-44,"Employed, full-time","Developer, back-end",100-499,United Kingdom of Great Britain and Northern Ireland,22.00,Other,21,21.00,Remote,College but no degree,Books / Physical media,96828.00,16-25,16-25

### Analysing Final DataFrame Data

In [81]:
import numpy as np

In [82]:
final_df.head()

,Developer_Type,Age,Employment,Job_Role,Organization_Size,Country,Work_Experience,Industry,Total_Coding_Experience,Professional_Coding_Exp,RemoteWork,Education_Level,Learning_Source,Income_in_$,Work_Experience_Group,Professional_Coding_Exp_Group
1,Professional,25-34,"Employed, full-time","Senior Executive (C-Suite, VP, etc.)",2-9,United States of America,10.00,"Information Services, IT, Software Development, or other Technology",18,9.00,Remote,Bachelor's Degree,Books / Physical media,285000.00,6-15,6-15
2,Professional,45-54,"Employed, full-time","Developer, back-end",5K-9999,United States of America,23.00,"Information Services, IT, Software Development, or other Technology",27,23.00,"Hybrid (some remote, some in-person)",Bachelor's Degree,Books / Physical media,250000.00,16-25,16-25
3,Professional,25-34,"Employed, full-time","Developer, front-end",100-499,United States of America,7.00,N/A,12,7.00,"Hybrid (some remote, some in-person)",Bachelor's Degree,Colleague,156000.00,6-15,6-15
4,Professional,25-34,"Employed, full-time","Developer, full-stack",20-99,Philippines,6.00,Other,6,4.00,Remote,Bachelor's Degree,Books / Physical media,23456.00,6-15,0-5
5,Professional,35-44,"Employed, full-time","Developer, back-end",100-499,United Kingdom of Great Britain and Northern Ireland,22.00,Other,21,21.00,Remote,College but no degree,Books / Physical media,96828.00,16-25,16-25

### Q1 - What Companies do the Developer get paid most?

In [83]:
final_df['Job_Role'].value_counts()

Developer, full-stack                            22809
Developer, back-end                              12497
Developer, front-end                              4305
Developer, desktop or enterprise applications     3561
Developer, mobile                                 2275
Other (please specify):                           2234
Engineering manager                               1952
Developer, embedded applications or devices       1672
Data scientist or machine learning specialist     1321
Senior Executive (C-Suite, VP, etc.)              1256
DevOps specialist                                 1242
Research & Development role                       1206
Engineer, data                                    1129
Cloud infrastructure engineer                      953
Academic researcher                                916
Developer, game or graphics                        686
N/A                                                680
Data or business analyst                           646
System administrator                               532
Developer, QA or test                              503
Project manager                                    470
Product manager                                    400
Engineer, site reliability                         392
Security professional                              378
Developer Experience                               298
Educator                                           291
Scientist                                          288
Blockchain                                         260
Hardware Engineer                                  233
Database administrator                             218
Designer                                           200
Developer Advocate                                 193
Marketing or sales professional                     88
Student                                             52
Name: Job_Role, dtype: int64

In [84]:
#Filtering data for the developer only job roles
developer_df = final_df.loc[final_df['Job_Role'].str.contains('Developer')].copy()

In [85]:
developer_df['Job_Role'].value_counts()

Developer, full-stack                            22809
Developer, back-end                              12497
Developer, front-end                              4305
Developer, desktop or enterprise applications     3561
Developer, mobile                                 2275
Developer, embedded applications or devices       1672
Developer, game or graphics                        686
Developer, QA or test                              503
Developer Experience                               298
Developer Advocate                                 193
Name: Job_Role, dtype: int64

In [86]:
developer_df['Industry'].value_counts()

N/A                                                                    22282
Information Services, IT, Software Development, or other Technology    13436
Financial Services                                                      3257
Other                                                                   2763
Manufacturing, Transportation, or Supply Chain                          1816
Healthcare                                                              1596
Retail and Consumer Services                                            1511
Advertising Services                                                     591
Insurance                                                                547
Higher Education                                                         529
Oil & Gas                                                                178
Legal Services                                                           157
Wholesale                                                                136
Name: Industry, dtype: int64

*Basis below we can clearly see the in companies like Advertising Services, Insurance, Healthcare and Financial Services the developers are paid most.*

In [87]:
# Using groupby we can get the findings
developer_df.groupby('Industry')['Income_in_$'].agg(np.mean).sort_values(ascending = False)

Industry
Advertising Services                                                  85321.67
Insurance                                                             83138.92
Healthcare                                                            82197.52
Financial Services                                                    82189.54
Retail and Consumer Services                                          79321.27
Other                                                                 78487.06
Oil & Gas                                                             71580.53
Legal Services                                                        70917.53
Information Services, IT, Software Development, or other Technology   70215.20
Manufacturing, Transportation, or Supply Chain                        68003.91
N/A                                                                   67211.46
Higher Education                                                      65358.83
Wholesale                                                             50371.58
Name: Income_in_$, dtype: float64

### Q2 - How much remote working matters to employee?

In [88]:
final_df['RemoteWork'].value_counts()

Hybrid (some remote, some in-person)    27794
Remote                                  27786
In-person                                9982
N/A                                       574
Name: RemoteWork, dtype: int64

*Majority of the People have been doing Remote work or Hybrid, also the average pay scale of these two is higher than In-person, hence people prefer Remote working more than In-person*

In [89]:
final_df[final_df['RemoteWork'] != 'N/A'].groupby('RemoteWork').agg(np.mean).sort_values(by='Income_in_$')

,Work_Experience,Professional_Coding_Exp,Income_in_$
RemoteWork,,,
In-person,6.09,9.34,46042.54
"Hybrid (some remote, some in-person)",7.30,10.89,72801.94
Remote,7.78,12.06,85012.11

### Q3 - How does coding experience affects level of pay?

*People with more coding experience get paid more, as per below 36-50 group get the highest salary among all group with average person have coding experience of 40.8 years*

In [90]:
final_df.groupby('Professional_Coding_Exp_Group')[['Professional_Coding_Exp', 'Income_in_$']].agg(np.mean).sort_values(by = 'Income_in_$',ascending=False)

                               Professional_Coding_Exp  Income_in_$
Professional_Coding_Exp_Group
36-50                                            40.82    131016.99
16-25                                            20.35     92149.28
26-35                                            30.03     83767.91
6-15                                              9.88     81225.45
0-5                                               3.19     50355.35

### Q4 - Whats the most populous method of learning?

*More people prefer Books or some type of physical media more helpful in learning about coding then other online platforms, more than 50% people prefer Books / Physical media as their prime source of learning*

In [91]:
final_df['Learning_Source'].value_counts()

Books / Physical media                                 36198
Online Courses or Certification                         8025
Colleague                                               5546
Other online resources (e.g., videos, blogs, forum)     4999
Job training                                            4656
Coding Bootcamp                                         2396
School or College                                       1820
Friend or family member                                 1138
Hackathons                                               776
Other                                                    582
Name: Learning_Source, dtype: int64

### Q5 - Are you more likely to get the job as developer if you own a master's degree?

In [92]:
# Table which only include Developer job roles
developer_df.pivot_table(index = 'Education_Level', columns = 'Job_Role', values= 'Employment', aggfunc = 'count' )

Job_Role,Developer Advocate,Developer Experience,"Developer, QA or test","Developer, back-end","Developer, desktop or enterprise applications","Developer, embedded applications or devices","Developer, front-end","Developer, full-stack","Developer, game or graphics","Developer, mobile"
Education_Level,,,,,,,,,,
Associate Degree,11.00,3.00,13.00,320.00,117.00,28.00,164.00,945.00,21.00,59.00
Bachelor's Degree,86.00,143.00,248.00,6253.00,1462.00,760.00,2242.00,11293.00,312.00,1212.00
College but no degree,15.00,28.00,47.00,1251.00,463.00,118.00,642.00,3026.00,73.00,223.00
Master's Degree,63.00,90.00,159.00,3642.00,1069.00,633.00,835.00,5190.00,187.00,631.00
Primary School,NaN,3.00,3.00,55.00,14.00,3.00,27.00,159.00,7.00,12.00
Professional Degree,8.00,14.00,12.00,416.00,174.00,77.00,64.00,581.00,20.00,50.00
Secondary School,6.00,14.00,19.00,452.00,201.00,42.00,273.00,1302.00,54.00,67.00
Something else,4.00,3.00,2.00,108.00,61.00,11.00,58.00,313.00,12.00,21.00

*As per the above step we can see the having master did not affect much in developer jobs, in some profile Master degree candidates are more other, but majorly Bachelor degree professional get more jobs than master in most cases.*

In [93]:
#Table include all the professions
final_df.pivot_table(index = 'Education_Level', columns = 'Job_Role', values= 'Employment', aggfunc = 'count' )

Job_Role,Academic researcher,Blockchain,Cloud infrastructure engineer,Data or business analyst,Data scientist or machine learning specialist,Database administrator,Designer,DevOps specialist,Developer Advocate,Developer Experience,"Developer, QA or test","Developer, back-end","Developer, desktop or enterprise applications","Developer, embedded applications or devices","Developer, front-end","Developer, full-stack","Developer, game or graphics","Developer, mobile",Educator,"Engineer, data","Engineer, site reliability",Engineering manager,Hardware Engineer,Marketing or sales professional,N/A,Other (please specify):,Product manager,Project manager,Research & Development role,Scientist,Security professional,"Senior Executive (C-Suite, VP, etc.)",Student,System administrator
Education_Level,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Associate Degree,2.00,6.00,39.00,19.00,5.00,13.00,10.00,45.00,11.00,3.00,13.00,320.00,117.00,28.00,164.00,945.00,21.00,59.00,6.00,24.00,12.00,33.00,3.00,7.00,23.00,58.00,17.00,9.00,7.00,NaN,13.00,30.00,1.00,33.00
Bachelor's Degree,65.00,100.00,445.00,271.00,325.00,102.00,86.00,567.00,86.00,143.00,248.00,6253.00,1462.00,760.00,2242.00,11293.00,312.00,1212.00,75.00,493.00,183.00,921.00,99.00,33.00,237.00,935.00,151.00,158.00,363.00,29.00,150.00,470.00,21.00,186.00
College but no degree,11.00,31.00,128.00,70.00,24.00,20.00,32.00,177.00,15.00,28.00,47.00,1251.00,463.00,118.00,642.00,3026.00,73.00,223.00,14.00,52.00,60.00,200.00,21.00,18.00,83.00,286.00,48.00,51.00,81.00,NaN,43.00,168.00,10.00,113.00
Master's Degree,322.00,94.00,252.00,219.00,689.00,63.00,49.00,316.00,63.00,90.00,159.00,3642.00,1069.00,633.00,835.00,5190.00,187.00,631.00,96.00,470.00,101.00,638.00,81.00,21.00,176.00,663.00,149.00,197.00,445.00,81.00,126.00,423.00,8.00,94.00
Primary School,12.00,NaN,9.00,2.00,3.00,NaN,2.00,7.00,NaN,3.00,3.00,55.00,14.00,3.00,27.00,159.00,7.00,12.00,3.00,3.00,1.00,7.00,1.00,NaN,11.00,6.00,1.00,NaN,2.00,1.00,4.00,9.00,1.00,9.00
Professional Degree,497.00,14.00,31.00,40.00,267.00,10.00,6.00,23.00,8.00,14.00,12.00,416.00,174.00,77.00,64.00,581.00,20.00,50.00,90.00,64.00,11.00,93.00,21.00,4.00,74.00,146.00,22.00,32.00,264.00,174.00,13.00,98.00,1.00,26.00
Secondary School,3.00,12.00,45.00,20.00,5.00,7.00,13.00,81.00,6.00,14.00,19.00,452.00,201.00,42.00,273.00,1302.00,54.00,67.00,5.00,15.00,22.00,50.00,6.00,4.00,39.00,99.00,10.00,15.00,35.00,3.00,22.00,47.00,9.00,51.00
Something else,4.00,3.00,4.00,5.00,3.00,3.00,2.00,26.00,4.00,3.00,2.00,108.00,61.00,11.00,58.00,313.00,12.00,21.00,2.00,8.00,2.00,10.00,1.00,1.00,37.00,41.00,2.00,8.00,9.00,NaN,7.00,11.00,1.00,20.00

*However, in case of all professions, we can see that professions which require high knowledge or degree have more candidates from Master or Professional degree than Bachelor ones. Researcher, Data Scientist, Project or Product Managers prefer candidates with Master's degree than any other.*

## References

- [Pandas Documentation](https://pandas.pydata.org/docs/index.html)
- [Stack OverFlow Annual Developer Survey](https://insights.stackoverflow.com/survey)